[package]
name = "simple-chat-app"
version = "0.1.0"
authors = ["hieunq <hieunq@ows.vn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ws = "0.7.8"